---
name: Build & Test using system packages

on:
  push:
    branches: [main]
    tags:
      - v**
  merge_group:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GTEST_COLOR: 1

jobs:
  test-system-linux:
    runs-on: ${{ matrix.config.os }}-${{ matrix.config.os-version }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu, os-version: '24.04', cxx: g++,     version: 12 }
          - { os: ubuntu, os-version: '24.04', cxx: g++,     version: 13 }
          - { os: ubuntu, os-version: '24.04', cxx: clang++, version: 16 }
          - { os: ubuntu, os-version: '24.04', cxx: clang++, version: 17 }
          - { os: ubuntu, os-version: '26.04', cxx: g++,     version: 14 }
          - { os: ubuntu, os-version: '26.04', cxx: g++,     version: 15 }
          - { os: ubuntu, os-version: '26.04', cxx: clang++, version: 21 }
          - { os: ubuntu, os-version: '26.04', cxx: clang++, version: 22 }
    env:
      CXX: ${{ matrix.config.cxx }}-${{ matrix.config.version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        with:
          key: ${{ github.job }}-${{ matrix.config.os }}-${{ matrix.config.os-version }}-${{ matrix.config.cxx }}-${{ matrix.config.version }}-${{ github.ref }}
          save: ${{ github.ref == 'refs/heads/main' }}
          max-size: 2G
          evict-old-files: 7d

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          os: ${{ matrix.config.os }}
          os-version: ${{ matrix.config.os-version }}

      - name: Build host
        uses: ./.github/actions/build
        with:
          workflow-preset: host-system

      - name: Build host and unit test
        uses: ./.github/actions/build
        with:
          workflow-preset: test-system

  test-system-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' }}
          max-size: 2G
          evict-old-files: 7d

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          os: macos
          os-version: latest

      - name: Build host
        uses: ./.github/actions/build
        with:
          workflow-preset: host-system

      - name: Build host and unit test
        uses: ./.github/actions/build
        with:
          workflow-preset: test-system

  test-system-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install build tools
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' }}
          variant: sccache
          max-size: 2G
          evict-old-files: 7d

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          os: windows
          os-version: latest

      - name: Build host
        uses: ./.github/actions/build
        with:
          workflow-preset: host-system

      - name: Build host and unit test
        uses: ./.github/actions/build
        with:
          workflow-preset: test-system
