---
name: Build & Test

on:
  push:
    branches: [main]
    tags:
      - v**
  merge_group:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GTEST_COLOR: 1

jobs:
  build-in-devcontainer:
    name: Devcontainer Build
    runs-on: [ubuntu-latest]
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.8.2@sha256:8d6d0b49bef9b1f572793dee8dcc05edcbe4f44f108f075640dda284ff3e2d4e # v6.8.2
    strategy:
      matrix:
        target: [Host, Windows]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - if: ${{ matrix.target == 'Windows' }}
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: cache-winsdk
        with:
          path: /winsdk
          key: cache-winsdk-10.0.26100-14.43.17.13
      - if: ${{ matrix.target == 'Windows' && steps.cache-winsdk.outputs.cache-hit != 'true' }}
        run: ./get-winsdk.sh
      - uses: hendrikmuhs/ccache-action@1bbbcda0748b3e340dee71a314fa68ffcbd6df79 # v1.2.21
        with:
          key: ${{ github.job }}
          max-size: 2G
      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: "${{ matrix.target}}"
          buildPreset: "${{ matrix.target}}-Release"

  test-linux:
    name: Acceptance Test on Linux
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.8.2@sha256:8d6d0b49bef9b1f572793dee8dcc05edcbe4f44f108f075640dda284ff3e2d4e # v6.8.2
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hendrikmuhs/ccache-action@1bbbcda0748b3e340dee71a314fa68ffcbd6df79 # v1.2.21
        with:
          key: ${{ github.job }}
          max-size: 2G
      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: "Host"
          buildPreset: "Host-Debug"
      - run: |
          bats --formatter junit cucumber_cpp/acceptance_test/test.bats | tee test-report.xml
      - uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          files: test-report.xml

  host_build_test:
    name: Host Build & Test
    runs-on: ${{ matrix.os }}-${{ matrix.version}}
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
        version: [latest]
        type: [synchronous]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: hendrikmuhs/ccache-action@1bbbcda0748b3e340dee71a314fa68ffcbd6df79 # v1.2.21
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 2G
      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          workflowPreset: "${{ matrix.os }}-Debug-${{ matrix.type }}"
      - name: Upload test logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: test-logs
          path: .build/${{ matrix.os }}-Debug-${{ matrix.type }}/Testing/Temporary/
