---
name: Build & Test

on:
  push:
    branches: [main]
    tags:
      - v**
  merge_group:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GTEST_COLOR: 1

jobs:
  build-in-devcontainer:
    name: Devcontainer Build
    runs-on: [ubuntu-latest]
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.10.2@sha256:6dcb2bba0b158b055995b728631e1b92c7e8bae97119b0f171429423ed9d5e19 # v6.10.2
    strategy:
      matrix:
        target: [Host, Windows]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - if: ${{ matrix.target == 'Windows' }}
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: cache-winsdk
        with:
          path: /winsdk
          key: cache-winsdk-10.0.26100-14.43.17.13
      - if: ${{ matrix.target == 'Windows' && steps.cache-winsdk.outputs.cache-hit != 'true' }}
        run: ./get-winsdk.sh
      - uses: hendrikmuhs/ccache-action@33522472633dbd32578e909b315f5ee43ba878ce # v1.2.22
        with:
          key: ${{ github.job }}-${{ matrix.target }}
          max-size: 2G
      - uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        with:
          configurePreset: "${{ matrix.target}}"
          buildPreset: "${{ matrix.target}}-Release"

  test-linux:
    name: Acceptance Test on Linux
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.10.2@sha256:6dcb2bba0b158b055995b728631e1b92c7e8bae97119b0f171429423ed9d5e19 # v6.10.2
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hendrikmuhs/ccache-action@33522472633dbd32578e909b315f5ee43ba878ce # v1.2.22
        with:
          key: ${{ github.job }}
          max-size: 2G
      - uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        with:
          configurePreset: "Host"
          buildPreset: "Host-Debug"
      - run: |
          bats --formatter junit cucumber_cpp/acceptance_test/test.bats | tee test-report.xml
      - uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          files: test-report.xml

  host_build_test:
    name: Host Build & Test
    runs-on: ${{ matrix.os }}-${{ matrix.version}}
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
        version: [latest]
        type: [synchronous]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: hendrikmuhs/ccache-action@33522472633dbd32578e909b315f5ee43ba878ce # v1.2.22
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 2G
      - uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        with:
          workflowPreset: "${{ matrix.os }}-Debug-${{ matrix.type }}"
      - name: Upload test logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-logs
          path: .build/${{ matrix.os }}-Debug-${{ matrix.type }}/Testing/Temporary/
