---
name: conventional-pr

on:
  merge_group:
  pull_request:

permissions: read-all

jobs:
  conventional_commit:
    runs-on: [ubuntu-latest]
    steps:
      - uses: Namchee/conventional-pr@497c801eb96ea7484971691e76f254886e3e1f32 # v0.15.5
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          body: false
          issue: false
          close: false
