---
name: conventional-pr

on:
  merge_group:
  pull_request:

permissions: read-all

jobs:
  conventional_commit:
    runs-on: [ubuntu-latest]
    steps:
      - uses: Namchee/conventional-pr@a6f50a1a97809e18975759853b67e45246005369 # v0.15.6
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          body: false
          issue: false
          close: false
