---
name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GTEST_COLOR: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/.cpm

jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-26.04
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Disable shallow clone to enable blame information
          persist-credentials: false

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          os: ubuntu
          os-version: 26.04

      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats bats-support bats-assert

      - name: Build host
        uses: ./.github/actions/build
        with:
          ccache-key: ${{ github.job }}
          workflow-preset: coverage
        env:
          CPM_SOURCE_CACHE: ${{ env.CPM_SOURCE_CACHE }}
          GTEST_OUTPUT: "xml:${{ github.workspace }}/testresults/"

      - uses: philips-software/sonarqube-issue-conversion@9e9958764ba5fd1d302b039779dc902bedfa4d01 # v1.2.0
        with:
          input: ${{ github.workspace }}/.build/coverage/sonarqube.xml
          output: execution.xml
          transformation: gtest-to-generic-execution

      - name: Convert results
        run: |
          cp .build/coverage/compile_commands.json compile_commands.json
          cp .build/coverage/sonarqube.xml sonarqube.xml

      - uses: sonarsource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Show coverage summary
        working-directory: cpp
        run: cat .build/coverage/coverage-summary.md

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: github/codeql-action/init@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          languages: cpp

      - name: Build
        uses: ./.github/actions/build
        with:
          cpm-source-cache: ${{ env.CPM_SOURCE_CACHE }}
          use-ccache: true
          ccache-key: ${{ github.job }}
          configure-preset: "Host"
          build-preset: "Host-Debug"

      - uses: github/codeql-action/analyze@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
