---
name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GTEST_COLOR: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/.cpm

jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    container: ghcr.io/philips-software/amp-devcontainer-cpp:8.1.0@sha256:740110a1a70c336d5b4a2770f84b9d856839ca90a04fec8f0300828e98cb9518
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Disable shallow clone to enable blame information
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/build-test
        with:
          cpm-source-cache: ${{ env.CPM_SOURCE_CACHE }}
          use-ccache: true
          ccache-key: ${{ github.job }}
          configure-preset: "Coverage"
          build-preset: "Coverage"
          test-preset: "Coverage"
        env:
          GTEST_OUTPUT: "xml:${{ github.workspace }}/testresults/"

      - name: Run acceptance tests
        run: |
          bats --formatter junit cucumber_cpp/acceptance_test/test.bats | tee test-report.xml

      - name: Check testdata coverage
        run: cmake --build .build/Coverage --target generate-coverage-report

      - uses: philips-software/sonarqube-issue-conversion@9e9958764ba5fd1d302b039779dc902bedfa4d01 # v1.2.0
        with:
          input: ${{ github.workspace }}/.build/Coverage/sonarqube.xml
          output: execution.xml
          transformation: gtest-to-generic-execution

      - name: Convert results
        run: |
          cp .build/Coverage/compile_commands.json compile_commands.json
          cp .build/Coverage/sonarqube.xml sonarqube.xml

      - uses: sonarsource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: github/codeql-action/init@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          languages: cpp

      - name: Build
        uses: ./.github/actions/build
        with:
          cpm-source-cache: ${{ env.CPM_SOURCE_CACHE }}
          use-ccache: true
          ccache-key: ${{ github.job }}
          configure-preset: "Host"
          build-preset: "Host-Debug"

      - uses: github/codeql-action/analyze@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
